🚨 Implement Display for Cookie instead of ToString
```
error: direct implementation of `ToString`
   --> src/bus/cookies.rs:222:1
    |
222 | / impl ToString for Cookie {
223 | |     fn to_string(&self) -> String {
224 | |         format!("{} {} {}", self.id, self.created, self.cookie)
225 | |     }
226 | | }
    | |_^
    |
    = help: prefer implementing `Display` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_trait_impl
    = note: `-D clippy::to-string-trait-impl` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::to_string_trait_impl)]`
```