⬆️  Update proc-macro2 to latest release
Otherwise, the build breaks against latest nightly:

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/zeenix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```